#ifndef BLEND_LAYER_INCLUDED
#define BLEND_LAYER_INCLUDED

// -----------------------------------------------------------------------------
// BlendLayer.hlsl
// Shared helper functions for layer blending and mask-atlas sampling across
// MrPath preview & runtime shaders.
// -----------------------------------------------------------------------------
// Author: Auto-generated by tooling – feel free to extend.
// -----------------------------------------------------------------------------

// Simple blend-mode enumeration (keep in sync with C# enum BlendMode)
// 0 = AlphaBlend, 1 = Additive, 2 = Multiply, 3 = Overlay (placeholder)
// Additional modes can be added here.

inline float4 ApplyBlend(float4 baseColor, float4 layerColor, float blendMode, float opacity)
{
    // Effective alpha from layer's alpha and per-layer opacity
    float layerAlpha = saturate(layerColor.a * opacity);

    // Candidate results for selection
    float3 alphaBlendRgb = lerp(baseColor.rgb, layerColor.rgb, layerAlpha);
    float3 addRgb        = baseColor.rgb + layerColor.rgb * layerAlpha;
    float3 mulRgb        = baseColor.rgb * lerp(1.0, layerColor.rgb, layerAlpha);

    float3 overlayRgbLow   = 2.0 * baseColor.rgb * layerColor.rgb;
    float3 overlayRgbHigh  = 1.0 - 2.0 * (1.0 - baseColor.rgb) * (1.0 - layerColor.rgb);
    float3 overlayBlendRgb = lerp(overlayRgbLow, overlayRgbHigh, step(0.5, baseColor.rgb));
    float3 screenRgb       = 1.0 - (1.0 - baseColor.rgb) * (1.0 - layerColor.rgb);

    float4 outColor = float4(baseColor.rgb, baseColor.a);

    // C# enum PathTool.Data.BlendMode:
    // 0: Normal, 1: Multiply, 2: Add, 3: Overlay, 4: Screen, 5: Lerp, 6: Additive
    outColor.rgb = (abs(blendMode - 0.0) < 0.5) ? alphaBlendRgb : outColor.rgb;                                   // Normal
    outColor.rgb = (abs(blendMode - 1.0) < 0.5) ? mulRgb        : outColor.rgb;                                   // Multiply
    outColor.rgb = (abs(blendMode - 2.0) < 0.5) ? addRgb        : outColor.rgb;                                   // Add
    outColor.rgb = (abs(blendMode - 3.0) < 0.5) ? lerp(baseColor.rgb, overlayBlendRgb, layerAlpha) : outColor.rgb; // Overlay
    outColor.rgb = (abs(blendMode - 4.0) < 0.5) ? lerp(baseColor.rgb, screenRgb, layerAlpha) : outColor.rgb;      // Screen
    outColor.rgb = (abs(blendMode - 5.0) < 0.5) ? alphaBlendRgb : outColor.rgb;                                   // Lerp
    outColor.rgb = (abs(blendMode - 6.0) < 0.5) ? addRgb        : outColor.rgb;                                   // Additive

    // 累积 Alpha（src-over）：base + (1 - base) * layerAlpha
    outColor.a = saturate(baseColor.a + (1.0 - baseColor.a) * layerAlpha);

    return saturate(outColor);
}

// -----------------------------------------------------------------------------
// SampleMaskAtlas
// Masks are packed vertically in a single atlas texture where each mask occupies
// a full-width strip with uniform height (1/_AtlasInvHeight). This helper
// converts canonical UV into atlas coordinates and applies threshold/scale.
// -----------------------------------------------------------------------------
// SampleMaskAtlas (2D with pathProgress)
// Each layer occupies a vertical slice of <pathSamples> rows.
// atlasInvHeight = 1.0 / (layerCount * pathSamples)
// -----------------------------------------------------------------------------
inline float SampleMaskAtlas2D(
    Texture2D    maskAtlas,
    SamplerState samp,
    float        across, // 0..1 distance across road (normalizedDist)
    float        pathProgress, // 0..1 along road
    float        layerIndex, // int but pass as float to avoid int ops
    float        pathSamples, // rows per layer
    float        atlasInvHeight)
{
    across = saturate(across);
    pathProgress = saturate(pathProgress);

	// Compute row index = layerIndex * pathSamples + pathProgress*(pathSamples-1)
	float row = layerIndex * pathSamples + pathProgress * (pathSamples - 1.0);
	// +0.5 for texel center
	float  v = (row + 0.5) * atlasInvHeight;
    float2 uvAtlas = float2(across, v);

    // 阈值塑形已在 MaskAtlas.compute/CPU 构建阶段完成，这里只读取原值
    float mask = maskAtlas.Sample(samp, uvAtlas).r;
    return saturate(mask);
}


#endif // BLEND_LAYER_INCLUDED
