#ifndef BLEND_LAYER_INCLUDED
#define BLEND_LAYER_INCLUDED

// -----------------------------------------------------------------------------
// BlendLayer.hlsl
// Shared helper functions for layer blending and mask-atlas sampling across
// MrPath preview & runtime shaders.
// -----------------------------------------------------------------------------
// Author: Auto-generated by tooling – feel free to extend.
// -----------------------------------------------------------------------------

// 简化混合模式：仅保留两种
// 0 = Override(Normal/AlphaBlend)
// 1 = Lerp（RGB 线性插值，Alpha 仍采用 src-over 累积）
inline float4 ApplyBlend(float4 baseColor, float4 layerColor, float blendMode, float opacity)
{
	float layerAlpha = saturate(layerColor.a * opacity);

	float3 overrideRgb = lerp(baseColor.rgb, layerColor.rgb, layerAlpha);
	float3 lerpRgb = lerp(baseColor.rgb, layerColor.rgb, layerAlpha);
	float3 olLow = 2.0 * baseColor.rgb * layerColor.rgb;
	float3 olHigh = 1.0 - 2.0 * (1.0 - baseColor.rgb) * (1.0 - layerColor.rgb);
	float3 overlayRgb = lerp(olLow, olHigh, step(0.5, baseColor.rgb));

	float4 outColor;
	// 统一 Alpha 规则：src-over 累积，保证视觉稳定
	outColor.a = saturate(baseColor.a + (1.0 - baseColor.a) * layerAlpha);
	// 选择 RGB 路径
	bool useLerp = (abs(blendMode - 1.0) < 0.5);
	bool useOverlay = (abs(blendMode - 2.0) < 0.5);
	outColor.rgb = useOverlay ? overlayRgb : (useLerp ? lerpRgb : overrideRgb);
	return saturate(outColor);
}

// -----------------------------------------------------------------------------
// SampleMaskAtlas
// Masks are packed vertically in a single atlas texture where each mask occupies
// a full-width strip with uniform height (1/_AtlasInvHeight). This helper
// converts canonical UV into atlas coordinates and applies threshold/scale.
// -----------------------------------------------------------------------------
// SampleMaskAtlas (2D with pathProgress)
// Each layer occupies a vertical slice of <pathSamples> rows.
// atlasInvHeight = 1.0 / (layerCount * pathSamples)
// -----------------------------------------------------------------------------
inline float SampleMaskAtlas2D(
	Texture2D    maskAtlas,
	SamplerState samp,
	float        across, // 0..1 distance across road (normalizedDist)
	float        pathProgress, // 0..1 along road
	float        layerIndex, // int but pass as float to avoid int ops
	float        pathSamples, // rows per layer
	float        atlasInvHeight)
{
	across = saturate(across);
	pathProgress = saturate(pathProgress);

	// Compute row index = layerIndex * pathSamples + pathProgress*(pathSamples-1)
	float row = layerIndex * pathSamples + pathProgress * (pathSamples - 1.0);
	// +0.5 for texel center
	float  v = (row + 0.5) * atlasInvHeight;
	float2 uvAtlas = float2(across, v);

	// 阈值塑形已在 MaskAtlas.compute/CPU 构建阶段完成，这里只读取原值
	float mask = maskAtlas.Sample(samp, uvAtlas).r;
	return saturate(mask);
}


#endif // BLEND_LAYER_INCLUDED
